### ISSUE TITLE
CocoaPods could not find compatible versions for pod "AppCenter"

### ISSUE THREAD

**Issue by unclev** [hanabi1224/flutter_appcenter_bundle#11]
I followed [Deploying Flutter apps via  AppCenter](https://buildflutter.com/deploying-flutter-apps-via-appcenter/) in part of _Build Configuration_, _Build Script_, and _AppCenter Setup_.

With an Android build the suggested _flutter_appcenter_bundle_ [Example](https://pub.dev/packages/flutter_appcenter_bundle#-example-tab-) works.

But iOS build in _App Center_ fails with

```
[!] CocoaPods could not find compatible versions for pod "AppCenter":
      In Podfile:
        flutter_appcenter_bundle (from `.symlinks/plugins/flutter_appcenter_bundle/ios`) was resolved to 0.0.1, which depends on
          AppCenter (~> 3.1)

    Specs satisfying the `AppCenter (~> 3.1)` dependency were found, but they required a higher minimum deployment target
```

and then

```
Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
```
I use _VS Code_ on Linux, and the project scaffolded with "Flutter: New Project". I do not have Mac OS X at hand to test iOS build locally.

As Podfile is supposed to be managed by Flutter, I have no idea how to solve this problem.

Am I missing something?

This issue seems to be a bug or incompatibility.

**Comment by dinovo** [comment]
I'm experiencing the same problem in AppCenter with latest release v3.1.0+1 of appcenter_bundle

As a temp. workaround have downgraded to v1.1.0+1

**Comment by hanabi1224** [comment]
You may need to manually remove podfile.lock and rebuild

**Comment by viliusvig** [comment]
Removing the podfile.lock helped, also needed to bump the minimum iOS version to >= 9.0 as it was required for pod install to work
