### ISSUE TITLE
Error in assembleDebug with flutter 1.17.3

### ISSUE THREAD

**Issue by faltrock-abone** [hanabi1224/flutter_appcenter_bundle#16]
Hi,

after upgrading flutter to the latest stable version I get a compile error upon executing `flutter run`:

`C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_appcenter_bundle-3.2.0+1\android\src\main\kotlin\com\github\hanabi1224\flutter_appcenter_bundle\FlutterAppcenterBundlePlugin.kt: (23, 58): Unresolved reference: binaryMessenger`

Apparently flutter changed how one gets access to the BinaryMessenger for communication with Dart: https://github.com/flutter/flutter/blob/4049889d9eecc8fb3eda316a5c371eeb636b2ae5/packages/flutter_tools/templates/plugin/android-kotlin.tmpl/src/main/kotlin/androidIdentifier/pluginClass.kt.tmpl#L22
When I manually fix the code to use `flutterPluginBinding.getFlutterEngine().getDartExecutor()` it works.

**Comment by hanabi1224** [comment]
Please try latest version with flutter 2, closing for now, plz re-open if there're still issues,thanks!
