### ISSUE TITLE
Google enforce inapp update rule

### ISSUE THREAD

**Issue by xylim666** [hanabi1224/flutter_appcenter_bundle#22]
Received this
"We are writing to let you know that Google Play now considers code for the 'in-app updates’ feature of App Center Distribute SDK a violation of its policy even if it is not used in run time. Please remove in-app updates from the Play store build of your app before October 16, 2020. After this date, Google Play will begin enforcing this new policy and could remove apps that violate it. "

Will it impact us?

https://app-center.intercom-clicks.com/via/e?ob=hbKoUbthUktfre7hm11DOK8cYTUW1UTPoUATnkl0Cs3S6%2BOVPFLW%2F4jfMjsbhpahCHARplEcSaUugCXFvYibj5SRAWJrweIrd9to9a4Z1OVwgWSe8XdO9swx5bXFD9m3IUNVGawM0c25oMCMMkziIA%3D%3D&h=4e68f26d811dc0f8f1d7d3bfae19de5abea85ed9-r33tq287_53577900009406&l=864a87a50f1d7b50fb11b2366f5500f51b254732-4477865

**Comment by hanabi1224** [comment]
Please check updated readme
