### ISSUE TITLE
unresolved supertypes: androidx.lifecycle.LifecycleOwner

### ISSUE THREAD

**Issue by ericgkr** [hanabi1224/flutter_appcenter_bundle#3]
When trying to build the example project for Android, i get error message as below. It looks like this one https://github.com/flutter/flutter/issues/46686 but not sure if they are the same. i also attach my Flutter env info below.

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
FLUTTER_ROOT: D:\Develop\flutter
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class io.flutter.embedding.engine.plugins.FlutterPlugin.FlutterPluginBinding, unresolved supertypes: androidx.lifecycle.LifecycleOwner
    class io.flutter.embedding.engine.FlutterEngine, unresolved supertypes: androidx.lifecycle.LifecycleOwner

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_appcenter_bundle:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1

flutter doctor -v output:
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18363.535], locale en-US)
    • Flutter version 1.9.1+hotfix.6 at D:\Develop\flutter
    • Framework revision 68587a0916 (4 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Develop\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\Develop\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.41.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

**Comment by hanabi1224** [comment]
@ericgkr Hmm, looks like it's some compatibility issue. I would suggest upgrading flutter sdk to latest stable (1.12.x).  This package was developed under flutter 1.12.x  so there's no test under older 1.9.x (CI build is setup for 1.12.x tho)

**Comment by ericgkr** [comment]
@hanabi1224 You are right. The issue is gone after upgrading to flutter 1.12.x. Many thanks!
