### ISSUE TITLE
Build error android/ios

### ISSUE THREAD

**Issue by p3root** [hanabi1224/flutter_appcenter_bundle#30]
Android
`
* What went wrong:
Could not determine the dependencies of task ':app:compileDevReleaseJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:devReleaseCompileClasspath'.
   > Could not resolve project :flutter_appcenter_bundle.
     Required by:
         project :app
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'env' with value 'dev', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm'. However we cannot choose between the following variants of project :flutter_appcenter_bundle:      
          - appCenterDebugAndroidTestCompile
          - appCenterDebugAndroidTestRuntime
          - appCenterDebugRuntime
          - appCenterDebugUnitTestCompile
          - appCenterDebugUnitTestRuntime
          - appCenterProfileRuntime
          - appCenterProfileUnitTestCompile
          - appCenterProfileUnitTestRuntime
          - appCenterReleaseApiElements
          - appCenterReleaseRuntime
          - appCenterReleaseRuntimeElements
          - appCenterReleaseUnitTestCompile
          - appCenterReleaseUnitTestRuntime
          - googlePlayDebugAndroidTestCompile
          - googlePlayDebugAndroidTestRuntime
          - googlePlayDebugRuntime
          - googlePlayDebugUnitTestCompile
          - googlePlayDebugUnitTestRuntime
          - googlePlayProfileRuntime
          - googlePlayProfileUnitTestCompile
          - googlePlayProfileUnitTestRuntime
          - googlePlayReleaseApiElements
          - googlePlayReleaseRuntime
          - googlePlayReleaseRuntimeElements
          - googlePlayReleaseUnitTestCompile
          - googlePlayReleaseUnitTestRuntime
        All of them match the consumer attributes:
          - Variant 'appCenterDebugAndroidTestCompile' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about env (required 'dev')     
                  - Doesn't say anything about its usage (required an API)
                  - Provides attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :flutter_appcenter_bundle' but the consumer didn't ask for it
          - Variant 'appCenterDebugAndroidTestRuntime' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about env (required 'dev')
                  - Doesn't say anything about its usage (required an API)
                  - Provides attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :flutter_appcenter_bundle' but the consumer didn't ask for it
          - Variant 'appCenterDebugRuntime' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about env (required 'dev')
                  - Doesn't say anything about its usage (required an API)
                  - Provides attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :flutter_appcenter_bundle' but the consumer didn't ask for it
          - Variant 'appCenterDebugUnitTestCompile' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about env (required 'dev')
                  - Doesn't say anything about its usage (required an API)
                  - Provides attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :flutter_appcenter_bundle' but the consumer didn't ask for it
          - Variant 'appCenterDebugUnitTestRuntime' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about env (required 'dev')
                  - Doesn't say anything about its usage (required an API)
                  - Provides attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :flutter_appcenter_bundle' but the consumer didn't ask for it
          - Variant 'appCenterProfileRuntime' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about env (required 'dev')
                  - Doesn't say anything about its usage (required an API)
                  - Provides attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :flutter_appcenter_bundle' but the consumer didn't ask for it
          - Variant 'appCenterProfileUnitTestCompile' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about env (required 'dev')
                  - Doesn't say anything about its usage (required an API)
                  - Provides attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :flutter_appcenter_bundle' but the consumer didn't ask for it
          - Variant 'appCenterProfileUnitTestRuntime' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about env (required 'dev')     
                  - Doesn't say anything about its usage (required an API)
                  - Provides attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :flutter_appcenter_bundle' but the consumer didn't ask for it
          - Variant 'appCenterReleaseApiElements' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'appCenterRelease' but the consumer didn't ask for it
                  - Provides attribute 'distribute' with value 'appCenter' but the consumer didn't ask for it
                  - Doesn't say anything about env (required 'dev')
          - Variant 'appCenterReleaseRuntime' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about env (required 'dev')
                  - Doesn't say anything about its usage (required an API)
                  - Provides attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :flutter_appcenter_bundle' but the consumer didn't ask for it
          - Variant 'appCenterReleaseRuntimeElements' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'appCenterRelease' but the consumer didn't ask for it
                  - Provides attribute 'distribute' with value 'appCenter' but the consumer didn't ask for it
                  - Doesn't say anything about env (required 'dev')
          - Variant 'appCenterReleaseUnitTestCompile' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about env (required 'dev')
                  - Doesn't say anything about its usage (required an API)
                  - Provides attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :flutter_appcenter_bundle' but the consumer didn't ask for it
          - Variant 'appCenterReleaseUnitTestRuntime' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about env (required 'dev')
                  - Doesn't say anything about its usage (required an API)
                  - Provides attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :flutter_appcenter_bundle' but the consumer didn't ask for it
          - Variant 'googlePlayDebugAndroidTestCompile' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a component, as well 
as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about env (required 'dev')
                  - Doesn't say anything about its usage (required an API)
                  - Provides attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :flutter_appcenter_bundle' but the consumer didn't ask for it
          - Variant 'googlePlayDebugAndroidTestRuntime' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a component, as well 
as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about env (required 'dev')
                  - Doesn't say anything about its usage (required an API)
                  - Provides attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :flutter_appcenter_bundle' but the consumer didn't ask for it
          - Variant 'googlePlayDebugRuntime' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about env (required 'dev')
                  - Doesn't say anything about its usage (required an API)
                  - Provides attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :flutter_appcenter_bundle' but the consumer didn't ask for it
          - Variant 'googlePlayDebugUnitTestCompile' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a component, as well as 
attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about env (required 'dev')
                  - Doesn't say anything about its usage (required an API)
                  - Provides attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :flutter_appcenter_bundle' but the consumer didn't ask for it
          - Variant 'googlePlayDebugUnitTestRuntime' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a component, as well as 
attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about env (required 'dev')
                  - Doesn't say anything about its usage (required an API)
                  - Provides attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :flutter_appcenter_bundle' but the consumer didn't ask for it
          - Variant 'googlePlayProfileRuntime' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about env (required 'dev')
                  - Doesn't say anything about its usage (required an API)
                  - Provides attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :flutter_appcenter_bundle' but the consumer didn't ask for it
          - Variant 'googlePlayProfileUnitTestCompile' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about env (required 'dev')
                  - Doesn't say anything about its usage (required an API)
                  - Provides attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :flutter_appcenter_bundle' but the consumer didn't ask for it
          - Variant 'googlePlayProfileUnitTestRuntime' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about env (required 'dev')
                  - Doesn't say anything about its usage (required an API)
                  - Provides attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :flutter_appcenter_bundle' but the consumer didn't ask for it
          - Variant 'googlePlayReleaseApiElements' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares an API of a component, as 
well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'googlePlayRelease' but the consumer didn't ask for it
                  - Provides attribute 'distribute' with value 'googlePlay' but the consumer didn't ask for it
                  - Doesn't say anything about env (required 'dev')
          - Variant 'googlePlayReleaseRuntime' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about env (required 'dev')
                  - Doesn't say anything about its usage (required an API)
                  - Provides attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :flutter_appcenter_bundle' but the consumer didn't ask for it
          - Variant 'googlePlayReleaseRuntimeElements' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a runtime of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Provides attribute 'com.android.build.api.attributes.VariantAttr' with value 'googlePlayRelease' but the consumer didn't ask for it
                  - Provides attribute 'distribute' with value 'googlePlay' but the consumer didn't ask for it
                  - Doesn't say anything about env (required 'dev')
          - Variant 'googlePlayReleaseUnitTestCompile' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about env (required 'dev')
                  - Doesn't say anything about its usage (required an API)
                  - Provides attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :flutter_appcenter_bundle' but the consumer didn't ask for it
          - Variant 'googlePlayReleaseUnitTestRuntime' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'release')
                  - Doesn't say anything about env (required 'dev')
                  - Doesn't say anything about its usage (required an API)
                  - Provides attribute 'org.jetbrains.kotlin.localToProject' with value 'local to :flutter_appcenter_bundle' but the consumer didn't ask for it
        The following variants were also considered but didn't match the requested attributes:
          - Variant 'appCenterDebugApiElements' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares an API of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release'
              - Other compatible attribute:
                  - Doesn't say anything about env (required 'dev')     
          - Variant 'appCenterDebugRuntimeElements' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a runtime of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release'
              - Other compatible attribute:
                  - Doesn't say anything about env (required 'dev')
          - Variant 'appCenterProfileApiElements' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares an API of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'profile' and the consumer 
needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release'
              - Other compatible attribute:
                  - Doesn't say anything about env (required 'dev')
          - Variant 'appCenterProfileRuntimeElements' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a runtime of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'profile' and the consumer 
needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release'
              - Other compatible attribute:
                  - Doesn't say anything about env (required 'dev')
          - Variant 'googlePlayDebugApiElements' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares an API of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release'
              - Other compatible attribute:
                  - Doesn't say anything about env (required 'dev')
          - Variant 'googlePlayDebugRuntimeElements' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a runtime of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release'
              - Other compatible attribute:
                  - Doesn't say anything about env (required 'dev')
          - Variant 'googlePlayProfileApiElements' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares an API of a component, as 
well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'profile' and the consumer 
needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release'
              - Other compatible attribute:
                  - Doesn't say anything about env (required 'dev')
          - Variant 'googlePlayProfileRuntimeElements' capability com.github.hanabi1224.flutter_appcenter_bundle:flutter_appcenter_bundle:1.0-SNAPSHOT declares a runtime of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm':
              - Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'profile' and the consumer 
needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release'
              - Other compatible attribute:
                  - Doesn't say anything about env (required 'dev')

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
`

iOS

`
[!] CocoaPods could not find compatible versions for pod "AppCenter":
                 In snapshot (Podfile.lock):
                   AppCenter (= 3.2.0, ~> 3.2.0)

`

**Comment by thingthing** [comment]
I got the same issue, i reverted the package version to 3.2.0+2 and it fixed the issue for now:
i put `flutter_appcenter_bundle: 3.2.0+2` in my pubspec.yaml, delete my pubspec.lock and do a flutter pub get afterwards

**Comment by NightOwlCoder** [comment]
hey guys, so I worked around this error by using this other library:

`https://github.com/vincenzosarnataro/app_center_bundle_sdk`

and adding this `implementation 'androidx.annotation:annotation:1.1.0'` to my `./android\app\build.gradle` dependencies session.

Hopes this hopes someone like me that got stuck with a urgent delivery :)

**Comment by michaelmairegger** [comment]
Same here with Flutter 2.0.2 and Dart 2.12.1

**Comment by progs** [comment]
Same issue here

```
Flutter 2.0.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8962f6dc68 (6 days ago) • 2021-03-11 13:22:20 -0800
Engine • revision 5d8bf811b3
Tools • Dart 2.12.1
```

**Comment by hanabi1224** [comment]
Regarding ios issue, manually delete pod.lock,
for android, are you able to build example project?

**Comment by hanabi1224** [comment]
Please check updated [readme](https://github.com/hanabi1224/flutter_appcenter_bundle/tree/master/flutter_appcenter_bundle)

**Comment by Lastmentor** [comment]
> I got the same issue, i reverted the package version to 3.2.0+2 and it fixed the issue for now:
> i put `flutter_appcenter_bundle: 3.2.0+2` in my pubspec.yaml, delete my pubspec.lock and do a flutter pub get afterwards

Was having the same problem after using this version it work for me.

**Comment by p3root** [comment]
Still got the same error.

> Please check updated readme
Already did ...still the same damn error
