### ISSUE TITLE
Abusing Policy Status of Google Play

### ISSUE THREAD

**Issue by oguzhanaksoy** [hanabi1224/flutter_appcenter_bundle#40]
From  Google Play Support&nbsp;&lt;no-reply-googleplay-developer@google.com&gt; 

Issue with your app
--
Your app contains content that doesn’t comply with the Device and Network Abuse policy. We found your app is using a non-compliant version of Microsoft Appcenter SDK contains code to download or install applications from unknown sources outside of Google Play.
Affected Version(s):
Version Code 16 &amp; 32

About the Device and Network Abuse policy
--
An app distributed via Google Play may not modify, replace, or update itself using any method other than Google Play's update mechanism. Likewise, an app may not download executable code (e.g. dex, JAR, .so files) from a source other than Google Play. Please note that you are responsible for all aspects of your app; by using an SDK in your app, you are responsible for how that SDK behaves within your app.

flutter_appcenter_bundle: 3.3.1+2

**Comment by joao10martins** [comment]
How did you solve this problem?

**Comment by joao10martins** [comment]
Hello? :)
